##
# Scans dependencies for known vulnarbilities using OWASP maven plugin nightly
##
name: Nightly Vulnarbility Scan
on:
  schedule:
    cron: "0 1 * * 1-5"

jobs:
  vulnarbility_scan:
    uses: medmera/shared-flows/.github/workflows/maven-vulnarbility-scan.yml@develop
    with:
      ref: 'master'
    secrets: inherit