name: GCP Terraform Merge PR

on:
  pull_request:
    types:
      - closed
    branches:
      - production
      - non-production
      - development
      - shared

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    uses: medmera/shared-flows/.github/workflows/post-link-to-flow-if-pr-merged.yml@develop
    with:
      linked-workflow-filename: 'gcp-terraform-release.yml'
      message: 'Apply job started for environment'
    secrets: inherit