name: Release
on:
  push:
    branches:
      - develop
    paths:
      - ".github/**"
      - "pom.xml"
      - "src/**"
jobs:
  release:
    uses: medmera/shared-flows/.github/workflows/ci/maven/maven-simple-release.yml@develop
    secrets: inherit