##
# Releases artifact automatically when code is pushed to the develop branch. This workflow is intended for simple testless builds.
##
name: Release
on:
  push:
    branches:
      - develop
    paths:
      - ".github/**"
      - "pom.xml"
      - "src/**"
jobs:
  release:
    uses: medmera/shared-flows/.github/workflows/maven-simple-release.yml@develop
    secrets: inherit