name: PR Merged

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    uses: medmera/java-flows/.github/workflows/maven-simple-merge-pr.yml@develop
    with:
      release-workflow-filename: 'maven-simple-release.yml'
    secrets: inherit