name: Verify
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
    paths:
      - ".github/**"
      - "pom.xml"
      - "src/**"
jobs:
  verify:
    uses: medmera/shared-flows/.github/workflows/maven-simple-verify.yml@develop
    secrets: inherit